### ISSUE TITLE
Enrollment Table / Model

### ISSUE THREAD

**Issue by ErisMik** [CodeTheChangeUBC/Chingari#15]
TODO: Unit Test this relation table

**Comment by Jimmy-Lin** [comment]
Added the model and db table through this commit: 38d46c872b56c3346d8037ae097559e32048adc2

Will write some unit tests to ensure relations are working correctly

**Comment by Jimmy-Lin** [comment]
Closing this issue since, it has been addressed as part of this PR for a different issue
https://github.com/CodeTheChangeUBC/Chingari/pull/60
