### ISSUE TITLE
Look into Lets Encrypt

### ISSUE THREAD

**Issue by ErisMik** [CodeTheChangeUBC/Chingari#20]
I found what looks like a good guide for setting up let's encrypt on our server: https://gorails.com/guides/free-ssl-with-rails-and-nginx-using-let-s-encrypt

Will test this out before this week's deployment

**Comment by ErisMik** [comment]
I believe there is a gem that simplifies this procedure even further
https://github.com/lgromanowski/acme-plugin

**Comment by ErisMik** [comment]
Let's Encrypt Certbot fully configured and deployed, chingari.org now has an ssl cert and handles https traffic

**Comment by Jimmy-Lin** [comment]
Issue has been validated. Production how accessible only through HTTPS (the security warning is due to remote assets which will be addressed in upcoming prod update)
