### ISSUE TITLE
Chingari logo CSS enlargement and scaling

### ISSUE THREAD

**Issue by ErisMik** [CodeTheChangeUBC/Chingari#26]
The logo should be enlarged a little and at certain bootstrap sizes it warps the image

**Comment by adilimtiaz** [comment]
Hey. This is what i managed to change to.
![screen shot 2018-03-14 at 10 48 26 pm](https://user-images.githubusercontent.com/22089117/37446402-034448d4-27da-11e8-9f10-e5e54e0000b2.png) 

And this is the original version. 
![screen shot 2018-03-14 at 10 51 28 pm](https://user-images.githubusercontent.com/22089117/37446453-4aeab740-27da-11e8-8626-6f25893eba23.png)

**Comment by Jimmy-Lin** [comment]
Much better! (y)
